services:

  frontend:
    image: gavrilukkirilo/ecommerce-frontend:v1
    ports:
      - "3000:80"

  service-registry:
    build: ./service-registry
    ports:
      - "8761:8761"
    networks:
      - ecommerce-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build: ./api-gateway
    ports:
      - "8765:8765"
    networks:
      - ecommerce-network
    env_file:
      - .env
    environment:
#      - JWT_SECRET=${JWT_SECRET}
      - EUREKA_URI=http://service-registry:8761/eureka/
    depends_on:
      service-registry:
        condition: service_healthy

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    networks:
      - ecommerce-network
    env_file:
      - .env
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - EUREKA_URI=http://service-registry:8761/eureka/
    depends_on:
      service-registry:
        condition: service_healthy
      user-db:
        condition: service_healthy

  product-service:
    build: ./product-service
    ports:
      - "8082:8082"
    networks:
      - ecommerce-network
    environment:
      - EUREKA_URI=http://service-registry:8761/eureka/
    depends_on:
      service-registry:
        condition: service_healthy
      redis:
        condition: service_healthy

  order-service:
    build: ./order-service
    ports:
      - "8083:8083"
    networks:
      - ecommerce-network
    environment:
      - EUREKA_URI=http://service-registry:8761/eureka/
    depends_on:
      service-registry:
        condition: service_healthy
      order-db:
        condition: service_healthy

  payment-service:
    build: ./payment-service
    ports:
      - "8084:8084"
    networks:
      - ecommerce-network
    environment:
      - EUREKA_URI=http://service-registry:8761/eureka/
    depends_on:
      service-registry:
        condition: service_healthy
      payment-db:
        condition: service_healthy

  notification-service:
    build: ./notification-service
    ports:
      - "8085:8085"
    networks:
      - ecommerce-network
    env_file:
      - .env
    environment:
      - EUREKA_URI=http://service-registry:8761/eureka/
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_USERNAME=${MAIL_USERNAME}
    depends_on:
      service-registry:
        condition: service_healthy


  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    networks:
      - ecommerce-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "2181" ]
      interval: 10s
      timeout: 5s
      retries: 5


  kafka:
    image: confluentinc/cp-kafka:7.4.0
    networks:
      - ecommerce-network
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    networks:
      - ecommerce-network
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    depends_on:
      - kafka


  #data-base
  user-db:
    image: postgres:17
    restart: always
    networks:
      - ecommerce-network
    volumes:
      - user-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=102836547
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d",  "userdb" ]
      interval: 10s
      timeout: 5s
      retries: 5

  order-db:
    image: postgres:17
    restart: always
    networks:
      - ecommerce-network
    volumes:
      - order-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=orderdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=102836547
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d",  "orderdb" ]
      interval: 10s
      timeout: 5s
      retries: 5

  payment-db:
    image: postgres:17
    restart: always
    networks:
      - ecommerce-network
    volumes:
      - payment-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=paymentdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=102836547
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d",  "paymentdb" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.6.4
    container_name: product_redis
    ports:
      - "6379:6379"
    networks:
      - ecommerce-network
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

networks:
  ecommerce-network:
    driver: bridge

volumes:
  user-db-data:
  order-db-data:
  payment-db-data:
  redis_data: