spring.application.name=user-service

server.port=8081

eureka.client.service-url.defaultZone=${EUREKA_URI}

spring.datasource.password=102836547
spring.datasource.username=postgres
#spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
spring.datasource.url=jdbc:postgresql://user-db:5432/userdb

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

jwt.secret=mojbardzoTrudnyINikomuNiewiadomykluczdoktoregoniktniemadostepu