spring.application.name=product-service
server.port=8082

spring.mongodb.uri=mongodb+srv://root:102836547@telusko.cua27o3.mongodb.net/productdb?retryWrites=true&w=majority&appName=telusko

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.redis.time-to-live=600000